apiVersion: v1
kind: Service
metadata:
  name: multiapp-nginx-nodeport
spec:
  selector:
    app: multi-container-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080   # допустимый диапазон 30000–32767
      protocol: TCP
