apiVersion: v1
kind: Service
metadata:
  name: multiapp-clusterip
spec:
  selector:
    app: multi-container-app
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
      protocol: TCP
    - name: multitool
      port: 9002
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
